version: '2'

services:
    web:
        container_name: qfs_nginx
        image: nginx:latest
        ports:
            - "8383:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        container_name: qfs_php
        image: php_qfs
        volumes:
            - ./code:/code
        networks:
            - code-network
    mongo:
        container_name: qfs_mongo
        image: mongo
        ports:
            - "27018:27017"
        volumes:
            - ./code:/code
        networks:
            - code-network
    elasticsearch:
        container_name: qfs_elasticsearch
        image: elasticsearch_qfs
        ports:
            - "9200:9200"
        networks:
            - code-network

    node:
        container_name: qfs_frontend
        image: node_qfs
        volumes:
            - ./code/frontend/app/src:/usr/src/app/src
            - ./code/frontend/app/index.html:/usr/src/app/index.html
            - ./code/frontend/app/webpack.config.js:/usr/src/app/webpack.config.js
        ports:
            - "3000:3000"
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
