version: '2'

services:
    web:
        container_name: qfs_nginx
        image: nginx_qfs
        ports:
            - "8383:80"
        volumes:
            - ./code/backend:/var/www/html/backend
            - ./nginx/qfs.conf:/etc/nginx/sites-enabled/default
        networks:
            - code-network

    php:
        container_name: qfs_php
        image: php_qfs
        volumes:
            - ./code/backend:/var/www/html/backend
        networks:
            - code-network

    mongo:
        container_name: qfs_mongo
        image: mongo
        ports:
            - "27018:27017"
        volumes:
            - ./code:/code
        networks:
            - code-network

    elasticsearch:
        container_name: qfs_elasticsearch
        image: elasticsearch_qfs
        ports:
            - "9203:9203"
        networks:
            - code-network

    node:
        container_name: qfs_frontend
        image: node_qfs
        volumes:
            - ./code/frontend/app/src:/usr/src/app/src
            - ./code/frontend/app/index.html:/usr/src/app/index.html
            - ./code/frontend/app/webpack.config.js:/usr/src/app/webpack.config.js
        ports:
            - "3000:3000"
        networks:
            - code-network

    mysql:
         container_name: qfs_mysql
         image: mysql
         environment:
            MYSQL_ROOT_PASSWORD: 4aeSFLJONzps6cIO
            MYSQL_DATABASE: qfs_search_dev
         ports:
            - "3307:3307"
         networks:
            - code-network

networks:
    code-network:
        driver: bridge
