<?php

namespace QFS\DBLogicBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * FlatRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class FlatRepository extends DocumentRepository
{
    public function findLatestItems()
    {
        return $this->findBy(['date' => ['$gte' => mktime(date('H') - 24)]]);
    }

    public function findByHash($hash)
    {
        return $this->findOneBy(['hash' => ['$eq' => $hash]]);
    }

    public function findByAlias($alias)
    {
        return $this->findOneBy(['alias' => ['$eq' => $alias]]);
    }
}
