<?php

namespace QFS\DBLogicBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * SourceLinkRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class SourceLinkRepository extends DocumentRepository
{
}
