business_logic_main_page:
    path:     /main
    defaults: { _controller: BusinessLogicBundle:MainPage:list }
detail_page:
    path:     /detail/{alias}
    defaults: { _controller: BusinessLogicBundle:MainPage:detail }