business_logic_main_page:
    path:     /main
    defaults: { _controller: BusinessLogicBundle:MainPage:list }
detail_page:
    path:     /detail/{id}
    defaults: { _controller: BusinessLogicBundle:Page:detail }