#db_logic:
#    resource: "@DBLogicBundle/Controller/"
#    type:     annotation
#    prefix:   /

#flat_parcer:
#    resource: "@FlatParserBundle/Controller/"
#    type:     annotation
#    prefix:   /

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation



NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: "/doc"

api:
    type: rest
    resource: "routing_api.yml"

BusinessLogicBundle:
    resource: "@BusinessLogicBundle/Resources/config/routing.yml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"